SET AUTOPRINT ON
DECLARE
	v_variable table.column_name%TYPE;
BEGIN
	DBMS_OUTPUT.PUT_LINE(''||v_variable);
EXCEPTION
	WHEN TOO_MANY_ROWS
		DBMS_OUTPUT.PUT_LINE('');
	WHEN NO_DATA_FOUND
	WHEN INVALID_CURSOR
	WHEN ZERO_DIVIDE
	WHEN DUP_VAL_ON_INDEX
	WHEN ACCES_INTO_NULL
	WHEN CASE_NOT_FOUND
	WHEN COLLECTION_IS_NULL
	WHEN CURSOR_ALREADY_OPEN
	WHEN DUP_VAL_ON_INDEX
	WHEN INVALID_NUMBER
	WHEN LOGIN_DENIED
	WHEN NO_DATA_FOUND
	(more info on page 8-12)
END;
/
